//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESPN3WMC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESPN3WMC.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Animations {
            get {
                object obj = ResourceManager.GetObject("Animations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Base {
            get {
                object obj = ResourceManager.GetObject("Base", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDisabled {
            get {
                object obj = ResourceManager.GetObject("ButtonDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDormant {
            get {
                object obj = ResourceManager.GetObject("ButtonDormant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLeftFocusOverlay {
            get {
                object obj = ResourceManager.GetObject("ButtonLeftFocusOverlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNoFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonPressedAfterGlow {
            get {
                object obj = ResourceManager.GetObject("ButtonPressedAfterGlow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonPressedHighlight {
            get {
                object obj = ResourceManager.GetObject("ButtonPressedHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRadioButtonBullet {
            get {
                object obj = ResourceManager.GetObject("ButtonRadioButtonBullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRadioButtonBulletFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonRadioButtonBulletFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRadioButtonBulletNoFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonRadioButtonBulletNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRadioButtonOutlineFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonRadioButtonOutlineFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRadioButtonOutlineNoFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonRadioButtonOutlineNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRightFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonRightFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRightFocusOverlay {
            get {
                object obj = ResourceManager.GetObject("ButtonRightFocusOverlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Colors {
            get {
                object obj = ResourceManager.GetObject("Colors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Controls {
            get {
                object obj = ResourceManager.GetObject("Controls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Error {
            get {
                return ResourceManager.GetStream("Error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap espn3_bg {
            get {
                object obj = ResourceManager.GetObject("espn3_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap espn3_logo {
            get {
                object obj = ResourceManager.GetObject("espn3_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] EventVideo {
            get {
                object obj = ResourceManager.GetObject("EventVideo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExpandCollapseButton {
            get {
                object obj = ResourceManager.GetObject("ExpandCollapseButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FindEditbox {
            get {
                object obj = ResourceManager.GetObject("FindEditbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FindEditboxNoFocus {
            get {
                object obj = ResourceManager.GetObject("FindEditboxNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxCheckedDisabled {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxCheckedDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxCheckedFocus {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxCheckedFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxCheckedNoFocus {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxCheckedNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxCheckedPressed {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxCheckedPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxUncheckedDisabled {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxUncheckedDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxUncheckedFocus {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxUncheckedFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxUncheckedNoFocus {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxUncheckedNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRunCheckBoxUncheckedPressed {
            get {
                object obj = ResourceManager.GetObject("FirstRunCheckBoxUncheckedPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Focus {
            get {
                return ResourceManager.GetStream("Focus", resourceCulture);
            }
        }
        
        internal static byte[] FontNames {
            get {
                object obj = ResourceManager.GetObject("FontNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Footer {
            get {
                object obj = ResourceManager.GetObject("Footer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GroupItem {
            get {
                object obj = ResourceManager.GetObject("GroupItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HeaderButton {
            get {
                object obj = ResourceManager.GetObject("HeaderButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HeaderText {
            get {
                object obj = ResourceManager.GetObject("HeaderText", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ListboxNoFocus {
            get {
                object obj = ResourceManager.GetObject("ListboxNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ListItem {
            get {
                object obj = ResourceManager.GetObject("ListItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream MiniSelect {
            get {
                return ResourceManager.GetStream("MiniSelect", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap OverlaysButtonNoFocus {
            get {
                object obj = ResourceManager.GetObject("OverlaysButtonNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PageTransition {
            get {
                return ResourceManager.GetStream("PageTransition", resourceCulture);
            }
        }
        
        internal static byte[] Pivot {
            get {
                object obj = ResourceManager.GetObject("Pivot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowLeft {
            get {
                object obj = ResourceManager.GetObject("PivotArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowLeftNoFocus {
            get {
                object obj = ResourceManager.GetObject("PivotArrowLeftNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowRight {
            get {
                object obj = ResourceManager.GetObject("PivotArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PivotArrowRightNoFocus {
            get {
                object obj = ResourceManager.GetObject("PivotArrowRightNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] PivotItem {
            get {
                object obj = ResourceManager.GetObject("PivotItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Select {
            get {
                return ResourceManager.GetStream("Select", resourceCulture);
            }
        }
        
        internal static byte[] SimpleButton {
            get {
                object obj = ResourceManager.GetObject("SimpleButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleCheckbox {
            get {
                object obj = ResourceManager.GetObject("SimpleCheckbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleEditbox {
            get {
                object obj = ResourceManager.GetObject("SimpleEditbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleRadioButton {
            get {
                object obj = ResourceManager.GetObject("SimpleRadioButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleRadioButtonGroup {
            get {
                object obj = ResourceManager.GetObject("SimpleRadioButtonGroup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleSpinner {
            get {
                object obj = ResourceManager.GetObject("SimpleSpinner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Sounds {
            get {
                object obj = ResourceManager.GetObject("Sounds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowBackDisabled {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowBackDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowBackDormant {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowBackDormant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowBackFocus {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowBackFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowBackFocusoverlay {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowBackFocusoverlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowBackNoFocus {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowBackNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowForwardDisabled {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowForwardDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowForwardDormant {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowForwardDormant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowForwardFocus {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowForwardFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowForwardFocusoverlay {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowForwardFocusoverlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerArrowForwardNoFocus {
            get {
                object obj = ResourceManager.GetObject("SpinnerArrowForwardNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerBluebarLargeDormant {
            get {
                object obj = ResourceManager.GetObject("SpinnerBluebarLargeDormant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerBluebarLargeFocus {
            get {
                object obj = ResourceManager.GetObject("SpinnerBluebarLargeFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpinnerBluebarLargeNoFocus {
            get {
                object obj = ResourceManager.GetObject("SpinnerBluebarLargeNoFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] TreeNodeItem {
            get {
                object obj = ResourceManager.GetObject("TreeNodeItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TreeViewHost {
            get {
                object obj = ResourceManager.GetObject("TreeViewHost", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
